# Generated by Django 4.2.6 on 2023-11-01 19:28

from django.db import migrations, models
import easybuy.models


class Migration(migrations.Migration):

    dependencies = [
        ('easybuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, validators=[easybuy.models.validate]),
        ),
    ]
